apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "170"
    field.cattle.io/creatorId: user-9ngsb
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-bl-billing
  name: bl-billing
spec:
  progressDeadlineSeconds: 120
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-bl-billing
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"bl-billing-hostport","hostPort":0,"kind":"NodePort","name":"8080tcp323100","protocol":"TCP","sourcePort":32310}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-bl-billing
    spec:
      containers:
      - args:
        - play
        env:
        - name: BL_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              key: BL_CONSUL_PORT
              name: bl-env
              optional: false
        - name: BL_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: BL_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              key: BL_CONSUL_HOST
              name: bl-env
              optional: false
        - name: BL_CONFIG_PROVIDER
          valueFrom:
            configMapKeyRef:
              key: BL_CONFIG_PROVIDER
              name: bl-env
              optional: false
        image: backendless/bl-billing:6.1.0.dev
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /webjars/springfox-swagger-ui/images/favicon-32x32.png
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        name: bl-billing
        ports:
        - containerPort: 8080
          name: 8080tcp323100
          protocol: TCP
        readinessProbe:
          failureThreshold: 60
          httpGet:
            path: /webjars/springfox-swagger-ui/images/favicon-32x32.png
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 1
          successThreshold: 2
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /opt/backendless/repo
          name: repo
        - mountPath: /opt/backendless/logs
          name: logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub-backendless
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/backendless/shared/repo
          type: ""
        name: repo
      - hostPath:
          path: /opt/backendless/shared/logs/bl-billing/
          type: ""
        name: logs
