apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: u-9qrz6
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-bl-game-server
  name: bl-game-server
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-bl-game-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":3030,"dnsName":"bl-game-server-hostport","hostPort":30300,"kind":"HostPort","name":"3030tcp303000","protocol":"TCP","sourcePort":30300}]]'
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-bl-game-server
    spec:
      containers:
      - env:
        - name: BL_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              key: BL_CONSUL_HOST
              name: bl-env
              optional: false
        - name: BL_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              key: BL_CONSUL_PORT
              name: bl-env
              optional: false
        - name: BL_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: BL_MANAGEMENT_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              key: BL_MANAGEMENT_HTTP_PORT
              name: bl-env
              optional: false
        image: backendless/bl-game-server:6.1.0.dev
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 2400
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 2
        name: bl-game-server
        ports:
        - containerPort: 3030
          hostPort: 30300
          name: 3030tcp303000
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: 2400
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 1
          successThreshold: 2
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: 	dockerhub-backendless
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
