apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: user-9ngsb
    deployment.kubernetes.io/revision: "53"
  generation: 72
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-bl-haproxy
  name: bl-haproxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-bl-haproxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"bl-haproxy-nodeport","kind":"NodePort","name":"80tcp322001","protocol":"TCP","sourcePort":32200},{"containerPort":16379,"dnsName":"bl-haproxy","kind":"ClusterIP","name":"16379tcp02","protocol":"TCP","sourcePort":0},{"containerPort":31017,"dnsName":"bl-haproxy","kind":"ClusterIP","name":"31017tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-bl-haproxy
    spec:
      containers:
      - image: haproxy:1.9
        imagePullPolicy: IfNotPresent
        name: bl-haproxy
        ports:
        - containerPort: 80
          name: 80tcp322001
          protocol: TCP
        - containerPort: 16379
          name: 16379tcp02
          protocol: TCP
        - containerPort: 31017
          name: 31017tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: config
      dnsPolicy: ClusterFirst
      hostAliases:
        - hostnames:
          - lcmpl-redis1      --> change to the real host
          ip: 51.77.33.105
        - hostnames:
          - lcmpl-redis2      --> change to the real host
          ip: 54.38.133.135
        - hostnames:
          - lcmpl-redis3      --> change to the real host
          ip: 51.77.61.45
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /opt/backendless/local/confs/haproxy/haproxy.cfg
          type: FileOrCreate
        name: config
