apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    field.cattle.io/creatorId: u-8dpmj
  labels:
    cattle.io/creator: norman
  name: bl-timer-runner
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          annotations:
            cattle.io/timestamp: 2019-07-22T14:54:48Z
          creationTimestamp: null
        spec:
          containers:
          - env:
            - name: BL_CONFIG_PROVIDER
              valueFrom:
                configMapKeyRef:
                  key: BL_CONFIG_PROVIDER
                  name: bl-env
            - name: BL_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  key: BL_CONSUL_HOST
                  name: bl-env
            - name: BL_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  key: BL_CONSUL_PORT
                  name: bl-env
            image: backendless/bl-server:5.7.3.11
            imagePullPolicy: IfNotPresent
            name: bl-timer-runner
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {}
              privileged: false
              procMount: Default
              readOnlyRootFilesystem: false
              runAsNonRoot: false
            stdin: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            tty: true
            volumeMounts:
            - mountPath: /opt/backendless/start.sh
              name: start
            - mountPath: /opt/backendless/repo
              name: repo
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - hostPath:
              path: /opt/backendless/shared/bl-timer/start.sh
              type: ""
            name: start
          - hostPath:
              path: /opt/backendless/shared/repo
              type: ""
            name: repo
  schedule: 03 15 * * *
  successfulJobsHistoryLimit: 10
  suspend: false
