apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: filebeat
  name: filebeat
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-03-28T16:59:19Z"
      creationTimestamp: null
      labels:
        k8s-app: filebeat
    spec:
      containers:
      - args:
        - -c
        - /opt/backendless/confs/filebeat/filebeat.yml
        - -e
        env:
        - name: ELASTICSEARCH_HOST
          value: elk.dal01.backendless.com
        - name: ELASTICSEARCH_PASSWORD
          value: changeme
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTIC_CLOUD_AUTH
        - name: ELASTIC_CLOUD_ID
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.elastic.co/beats/filebeat:7.6.0
        imagePullPolicy: IfNotPresent
        name: filebeat
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          capabilities: {}
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/backendless/confs/filebeat/filebeat.yml
          name: config
          readOnly: true
          subPath: filebeat.yml
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /opt/backendless/logs
          name: varlog
          readOnly: true
        - mountPath: /usr/share/filebeat/data
          name: data
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostAliases:
      - hostnames:
        - elk.dal01.backendless.com
        ip: 10.1.1.28
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 384
          name: filebeat-config
        name: config
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /opt/backendless/logs
          type: ""
        name: varlog
      - hostPath:
          path: /opt/backendless/filebeat/data
          type: DirectoryOrCreate
        name: data
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 3
  desiredNumberScheduled: 3
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  observedGeneration: 17
  updatedNumberScheduled: 3
