apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: infinispan-jgroups-dns-ping
  namespace: default
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ping
    port: 7800
    protocol: TCP
    targetPort: 7800
  publishNotReadyAddresses: true
  selector:
    has-infinispan: "true"
  sessionAffinity: None
  type: ClusterIP
