apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxysql
  app: proxysql-app
spec:
  serviceName: "proxysql"
  replicas: 1
  selector:
  front: proxysql
  template:
    metadata:
      name: proxysql
      labels:
        app: proxysql
        front: proxysql
    spec:
      containers:
        - name: proxysql
          image: perconalab/proxysql-k8s:latest
          ports:
            - containerPort: 3306
              name: mysql
            - containerPort: 6032
              name: proxyadm
          volumeMounts:
            - name: proxydata
              mountPath: /var/lib/proxysql
              subPath: data
          env:
            - name: CLUSTER_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-passwords
                  key: root
            - name: MYSQL_PROXY_USER
              value: "proxyuser"
            - name: MYSQL_PROXY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-passwords
                  key: proxyuser
            - name: PEERS
              value: mysql-0.pxc,mysql-1.pxc,mysql-2.pxc
          lifecycle:
            postStart:
              exec:
                command: ["/usr/bin/add_cluster_nodes.sh"]
      volumes:
        - hostPath:
            path: /opt/backendless/local/pxc-proxysql/data
            type: ""
          name: proxydata
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxysql
  name: sql
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: proxyadm
      port: 6032
      protocol: TCP
      targetPort: 6032
  selector:
    front: proxysql